from rest_framework import serializers


class DetallePersonalSerializer(serializers.Serializer):
    resultado = serializers.CharField()
    mensaje = serializers.CharField(allow_null=True)
    tipo_consulta = serializers.CharField(allow_null=True)
    codigo_persona = serializers.IntegerField(allow_null=True)
    dni_persona = serializers.CharField(allow_null=True)
    nombres_persona = serializers.CharField(allow_null=True)
    codigo_cargo = serializers.IntegerField(allow_null=True)
    cargo = serializers.CharField(allow_null=True)
    codigo_tipo_documento = serializers.IntegerField(allow_null=True)
    tipo_documento = serializers.CharField(allow_null=True)
    codigo_empresa = serializers.IntegerField(allow_null=True)
    empresa = serializers.CharField(allow_null=True)
    codigo_mov_sgt = serializers.IntegerField(allow_null=True)
    codigo_autorizante = serializers.IntegerField(allow_null=True)
    autorizante = serializers.CharField(allow_null=True, allow_blank=True)
    codigo_motivo = serializers.IntegerField(allow_null=True)
    motivo = serializers.CharField(allow_null=True)
    codigo_area = serializers.IntegerField(allow_null=True)
    area = serializers.CharField(allow_null=True)
    codigo_tipo_persona = serializers.IntegerField(allow_null=True)
    tipo_persona = serializers.CharField(allow_null=True)
    codigo_servicio = serializers.IntegerField(allow_null=True)
    codigo_cliente_control = serializers.IntegerField(allow_null=True)
    img = serializers.CharField(allow_null=True)
    nro_pase = serializers.CharField(allow_null=True)
